theme: jekyll-theme-tactile
title: Alexander Shaduri
description: Professional C++ and Rust Developer
show_downloads: false

# Sitemap
url: "https://shaduri.dev" # the base hostname & protocol for your site
plugins:
  - jekyll-sitemap
